project_id    = "awesome-gist-402911"
region        = "us-west4-b"
cluster_name  = "my-gke-cluster"
vpc_name       = "my-vpc"
subnet_name    = "my-subnet"
node_pool_name = "default-pool"
machine_type   = "e2-medium"
